[package]
name = "img-corroder"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.23"
clap = { version = "4.4.7", features = ["derive"] }
rand = "0.8.5"
asdf-pixel-sort = "0.2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
simple-base64 = "0.23"